on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cross
        run: cargo install cross
      - name: Create Artifact
        run: |
          cross build --release --locked --target x86_64-pc-windows-gnu 
          mkdir dist
          cp target/x86_64-pc-windows-gnu/release/xed.exe dist/
          cp LICENSE dist/LICENSE.txt
          cd dist
          zip -r xed-windows xed.exe LICENSE.txt
          cd ..
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.2
          bin/hub release edit -a "dist/xed-windows.zip" -m ${GITHUB_REF#refs/tags/} ${GITHUB_REF#refs/tags/}
